from datetime import date, datetime
from typing import Optional
from uuid import UUID
import uuid

from pydantic import BaseModel


class BizEntityOut(BaseModel):
    be_type: str
    be_name: str
    be_logo: Optional[str] = None
    be_contact: Optional[str] = None
    be_contact_title: Optional[str] = None
    be_address: Optional[str] = None
    be_email: Optional[str] = None
    be_phone: Optional[str] = None
    be_website: Optional[str] = None
    be_biz_number: Optional[str] = None
    be_tax_id: Optional[str] = None
    be_bank_info: Optional[str] = None
    be_payment_term: Optional[int] = None
    be_currency: Optional[str] = None
    be_inv_template_id: Optional[str] = None
    be_description: Optional[str] = None
    be_note: Optional[str] = None
    be_timezone: Optional[str] = None
    be_date_format: Optional[str] = None
    be_inv_prefix: Optional[str] = None
    be_inv_integer: Optional[int] = None
    be_inv_integer_max: Optional[int] = None
    be_show_paid_stamp: Optional[bool] = None
    be_plan_id: Optional[UUID] = uuid.UUID("00000000-0000-0000-0000-000000000001")
    be_plan_name: Optional[str] = None
    be_plan251_expired: Optional[datetime] = None
    be_plan252_expired: Optional[datetime] = None
    be_plan253_expired: Optional[datetime] = None
    be_plan254_expired: Optional[datetime] = None
    be_plan255_expired: Optional[datetime] = None
    be_plan256_expired: Optional[datetime] = None
    be_plan257_expired: Optional[datetime] = None
    be_plan258_expired: Optional[datetime] = None
    be_plan259_expired: Optional[datetime] = None
    be_number: Optional[str] = None
    payroll_account_number: Optional[str] = None
    province: Optional[str] = None
    country: Optional[str] = None
    street_address: Optional[str] = None
    city: Optional[str] = None
    postal_code: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    wsib_number: Optional[str] = None
    eht_account: Optional[str] = None
    remittance_frequency: Optional[str] = None
    tax_year_end: Optional[date] = None
    legal_name: Optional[str] = None
    operating_name: Optional[str] = None
    business_type: Optional[str] = None
    incorporation_date: Optional[date] = None
    employee_count: Optional[int] = None
    stripe_customer_id: Optional[str] = None
    stripe_subscription_id: Optional[str] = None
    stripe_price_id: Optional[str] = None
    stripe_status: Optional[str] = None
    stripe_current_period_end: Optional[datetime] = None
    stripe_cancel_at_period_end: Optional[bool] = None
    stripe_cancel_at: Optional[datetime] = None
    stripe_plan_key: Optional[str] = None
    stripe_interval: Optional[str] = None
    stripe_latest_event_id: Optional[str] = None


class BizEntityUpdate(BaseModel):
    be_type: Optional[str] = None
    be_name: Optional[str] = None
    be_logo: Optional[str] = None
    be_contact: Optional[str] = None
    be_contact_title: Optional[str] = None
    be_address: Optional[str] = None
    be_email: Optional[str] = None
    be_phone: Optional[str] = None
    be_website: Optional[str] = None
    be_biz_number: Optional[str] = None
    be_tax_id: Optional[str] = None
    be_bank_info: Optional[str] = None
    be_payment_term: Optional[int] = None
    be_currency: Optional[str] = None
    be_inv_template_id: Optional[str] = None
    be_description: Optional[str] = None
    be_note: Optional[str] = None
    be_timezone: Optional[str] = None
    be_date_format: Optional[str] = None
    be_inv_prefix: Optional[str] = None
    be_inv_integer: Optional[int] = None
    be_inv_integer_max: Optional[int] = None
    be_show_paid_stamp: Optional[bool] = None
    be_plan_id: Optional[UUID] = None
    be_plan_name: Optional[str] = None
    be_plan251_expired: Optional[datetime] = None
    be_plan252_expired: Optional[datetime] = None
    be_plan253_expired: Optional[datetime] = None
    be_plan254_expired: Optional[datetime] = None
    be_plan255_expired: Optional[datetime] = None
    be_plan256_expired: Optional[datetime] = None
    be_plan257_expired: Optional[datetime] = None
    be_plan258_expired: Optional[datetime] = None
    be_plan259_expired: Optional[datetime] = None
    be_number: Optional[str] = None
    payroll_account_number: Optional[str] = None
    province: Optional[str] = None
    country: Optional[str] = None
    street_address: Optional[str] = None
    city: Optional[str] = None
    postal_code: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    wsib_number: Optional[str] = None
    eht_account: Optional[str] = None
    remittance_frequency: Optional[str] = None
    tax_year_end: Optional[date] = None
    legal_name: Optional[str] = None
    operating_name: Optional[str] = None
    business_type: Optional[str] = None
    incorporation_date: Optional[date] = None
    employee_count: Optional[int] = None
    stripe_customer_id: Optional[str] = None
    stripe_subscription_id: Optional[str] = None
    stripe_price_id: Optional[str] = None
    stripe_status: Optional[str] = None
    stripe_current_period_end: Optional[datetime] = None
    stripe_cancel_at_period_end: Optional[bool] = None
    stripe_cancel_at: Optional[datetime] = None
    stripe_plan_key: Optional[str] = None
    stripe_interval: Optional[str] = None
    stripe_latest_event_id: Optional[str] = None
