"""init3

Revision ID: 03197a06b7cb
Revises: e312ec949cc5
Create Date: 2026-04-11 20:46:46.073784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03197a06b7cb'
down_revision: Union[str, None] = 'e312ec949cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_inv_invoice_payment_usr_id'), table_name='invoice_payment', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_payment_ten_id'), table_name='invoice_payment', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_payment_inv_id'), table_name='invoice_payment', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_payment_id'), table_name='invoice_payment', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_payment_created_by'), table_name='invoice_payment', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_payment_biz_id'), table_name='invoice_payment', schema='too_inv')
    op.drop_table('invoice_payment', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_item_usr_id'), table_name='invoice_item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_item_ten_id'), table_name='invoice_item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_item_inv_id'), table_name='invoice_item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_item_id'), table_name='invoice_item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_item_created_by'), table_name='invoice_item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_item_biz_id'), table_name='invoice_item', schema='too_inv')
    op.drop_table('invoice_item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_usr_id'), table_name='invoice', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_ten_id'), table_name='invoice', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_id'), table_name='invoice', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_created_by'), table_name='invoice', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_client_id'), table_name='invoice', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_biz_id'), table_name='invoice', schema='too_inv')
    op.drop_table('invoice', schema='too_inv')
    op.drop_index(op.f('ix_too_global_zuser_client_usr_id'), table_name='zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_client_ten_id'), table_name='zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_client_id'), table_name='zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_client_created_by'), table_name='zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_client_biz_id'), table_name='zuser_client', schema='too_global')
    op.drop_table('zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_t4_t4_employee_usr_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_ten_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_created_by'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_biz_id'), table_name='t4_employee', schema='too_t4')
    op.drop_table('t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_inv_item_usr_id'), table_name='item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_item_ten_id'), table_name='item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_item_id'), table_name='item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_item_created_by'), table_name='item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_item_biz_id'), table_name='item', schema='too_inv')
    op.drop_table('item', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_itax_usr_id'), table_name='itax', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_itax_ten_id'), table_name='itax', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_itax_id'), table_name='itax', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_itax_created_by'), table_name='itax', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_itax_biz_id'), table_name='itax', schema='too_inv')
    op.drop_table('itax', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_iplan_usr_id'), table_name='iplan', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_iplan_ten_id'), table_name='iplan', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_iplan_id'), table_name='iplan', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_iplan_created_by'), table_name='iplan', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_iplan_biz_id'), table_name='iplan', schema='too_inv')
    op.drop_table('iplan', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ipayment_method_usr_id'), table_name='ipayment_method', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ipayment_method_ten_id'), table_name='ipayment_method', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ipayment_method_id'), table_name='ipayment_method', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ipayment_method_created_by'), table_name='ipayment_method', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ipayment_method_biz_id'), table_name='ipayment_method', schema='too_inv')
    op.drop_table('ipayment_method', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ifee_usr_id'), table_name='ifee', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ifee_ten_id'), table_name='ifee', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ifee_id'), table_name='ifee', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ifee_created_by'), table_name='ifee', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ifee_biz_id'), table_name='ifee', schema='too_inv')
    op.drop_table('ifee', schema='too_inv')
    op.drop_index(op.f('ix_too_global_zuser_usr_id'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_ten_id'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_id'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_email'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_created_by'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_biz_id'), table_name='zuser', schema='too_global')
    op.drop_table('zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_usr_id'), table_name='zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_ten_id'), table_name='zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_id'), table_name='zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_created_by'), table_name='zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_biz_id'), table_name='zclient', schema='too_global')
    op.drop_table('zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_usr_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_ten_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_stripe_subscription_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_stripe_customer_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_created_by'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_biz_id'), table_name='zbe', schema='too_global')
    op.drop_table('zbe', schema='too_global')
    # ### end Alembic commands ###
