"""1024

Revision ID: 04a2ed89e97f
Revises: c91f2b6e4d10
Create Date: 2026-04-26 01:01:39.574168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '04a2ed89e97f'
down_revision: Union[str, None] = 'c91f2b6e4d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_1024',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk', sa.Text(), nullable=False),
    sa.Column('text_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('emb1024', Vector(dim=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_hnsw', 'inv_1024', ['emb1024'], unique=False, schema='too_ai', postgresql_using='hnsw', postgresql_ops={'emb1024': 'vector_cosine_ops'})
    op.create_index(op.f('ix_too_ai_inv_1024_id'), 'inv_1024', ['id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_source_id'), 'inv_1024', ['source_id'], unique=False, schema='too_ai')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_too_ai_inv_1024_source_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index('ix_emb1024_hnsw', table_name='inv_1024', schema='too_ai', postgresql_using='hnsw', postgresql_ops={'emb1024': 'vector_cosine_ops'})
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.drop_table('inv_1024', schema='too_ai')
    # ### end Alembic commands ###
