"""init

Revision ID: 11490414f015
Revises: 
Create Date: 2026-04-11 20:20:02.915022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '11490414f015'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS too_ainvoaic")
    op.execute("CREATE SCHEMA IF NOT EXISTS too_global")
    op.create_table('ai_cache',
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'cache_key', name='uq_agent_cache_ten_key')
    )
    op.create_index(op.f('ix_ai_cache_biz_id'), 'ai_cache', ['biz_id'], unique=False)
    op.create_index(op.f('ix_ai_cache_cache_key'), 'ai_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_ai_cache_created_by'), 'ai_cache', ['created_by'], unique=False)
    op.create_index(op.f('ix_ai_cache_expires_at'), 'ai_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ai_cache_id'), 'ai_cache', ['id'], unique=False)
    op.create_index(op.f('ix_ai_cache_ten_id'), 'ai_cache', ['ten_id'], unique=False)
    op.create_index(op.f('ix_ai_cache_usr_id'), 'ai_cache', ['usr_id'], unique=False)
    op.create_table('fee',
    sa.Column('fee_name', sa.String(length=128), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fee_note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ainvoaic'
    )
    op.create_index(op.f('ix_too_ainvoaic_fee_biz_id'), 'fee', ['biz_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_fee_created_by'), 'fee', ['created_by'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_fee_id'), 'fee', ['id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_fee_ten_id'), 'fee', ['ten_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_fee_usr_id'), 'fee', ['usr_id'], unique=False, schema='too_ainvoaic')
    op.create_table('i_payment_method',
    sa.Column('pm_name', sa.String(length=128), nullable=True),
    sa.Column('pm_note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ainvoaic'
    )
    op.create_index(op.f('ix_too_ainvoaic_i_payment_method_biz_id'), 'i_payment_method', ['biz_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_i_payment_method_created_by'), 'i_payment_method', ['created_by'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_i_payment_method_id'), 'i_payment_method', ['id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_i_payment_method_ten_id'), 'i_payment_method', ['ten_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_i_payment_method_usr_id'), 'i_payment_method', ['usr_id'], unique=False, schema='too_ainvoaic')
    op.create_table('item',
    sa.Column('item_number', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=256), nullable=True),
    sa.Column('item_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('item_unit_of_measure', sa.String(length=64), nullable=True),
    sa.Column('item_unit', sa.String(length=64), nullable=True),
    sa.Column('item_sku', sa.String(length=128), nullable=True),
    sa.Column('item_description', sa.String(length=1024), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('item_note', sa.String(length=1024), nullable=True),
    sa.Column('item_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ainvoaic'
    )
    op.create_index(op.f('ix_too_ainvoaic_item_biz_id'), 'item', ['biz_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_item_created_by'), 'item', ['created_by'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_item_id'), 'item', ['id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_item_ten_id'), 'item', ['ten_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_item_usr_id'), 'item', ['usr_id'], unique=False, schema='too_ainvoaic')
    op.create_table('plans',
    sa.Column('plan_code', sa.String(length=64), nullable=True),
    sa.Column('plan_name', sa.String(length=128), nullable=True),
    sa.Column('plan_price', sa.String(length=64), nullable=True),
    sa.Column('plan_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ainvoaic'
    )
    op.create_index(op.f('ix_too_ainvoaic_plans_biz_id'), 'plans', ['biz_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_plans_created_by'), 'plans', ['created_by'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_plans_id'), 'plans', ['id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_plans_ten_id'), 'plans', ['ten_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_plans_usr_id'), 'plans', ['usr_id'], unique=False, schema='too_ainvoaic')
    op.create_table('taxes',
    sa.Column('tax_name', sa.String(length=128), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('tax_type', sa.String(length=64), nullable=True),
    sa.Column('tax_note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ainvoaic'
    )
    op.create_index(op.f('ix_too_ainvoaic_taxes_biz_id'), 'taxes', ['biz_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_taxes_created_by'), 'taxes', ['created_by'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_taxes_id'), 'taxes', ['id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_taxes_ten_id'), 'taxes', ['ten_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_taxes_usr_id'), 'taxes', ['usr_id'], unique=False, schema='too_ainvoaic')
    op.create_table('zclient',
    sa.Column('client_number', sa.String(length=64), nullable=True),
    sa.Column('client_business_number', sa.String(length=128), nullable=True),
    sa.Column('client_company_name', sa.String(length=256), nullable=True),
    sa.Column('client_contact_name', sa.String(length=128), nullable=True),
    sa.Column('client_contact_title', sa.String(length=128), nullable=True),
    sa.Column('client_address', sa.String(length=512), nullable=True),
    sa.Column('client_email', sa.String(length=128), nullable=True),
    sa.Column('client_mainphone', sa.String(length=64), nullable=True),
    sa.Column('client_secondphone', sa.String(length=64), nullable=True),
    sa.Column('client_fax', sa.String(length=64), nullable=True),
    sa.Column('client_website', sa.String(length=256), nullable=True),
    sa.Column('client_currency', sa.String(length=16), nullable=True),
    sa.Column('client_tax_id', sa.String(length=128), nullable=True),
    sa.Column('client_payment_term', sa.Integer(), nullable=True),
    sa.Column('client_payment_method', sa.String(length=64), nullable=True),
    sa.Column('client_template_id', sa.String(length=32), nullable=True),
    sa.Column('client_terms_conditions', sa.String(length=1024), nullable=True),
    sa.Column('client_note', sa.String(length=1024), nullable=True),
    sa.Column('client_status', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_global'
    )
    op.create_index(op.f('ix_too_global_zclient_biz_id'), 'zclient', ['biz_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zclient_created_by'), 'zclient', ['created_by'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zclient_id'), 'zclient', ['id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zclient_ten_id'), 'zclient', ['ten_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zclient_usr_id'), 'zclient', ['usr_id'], unique=False, schema='too_global')
    op.create_table('zuser',
    sa.Column('plan_type', sa.String(length=64), nullable=True),
    sa.Column('plan_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('reddit', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pin', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('tax_no', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_global'
    )
    op.create_index(op.f('ix_too_global_zuser_biz_id'), 'zuser', ['biz_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_created_by'), 'zuser', ['created_by'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_email'), 'zuser', ['email'], unique=True, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_id'), 'zuser', ['id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_ten_id'), 'zuser', ['ten_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_usr_id'), 'zuser', ['usr_id'], unique=False, schema='too_global')
    op.create_table('invoice',
    sa.Column('inv_number', sa.String(length=64), nullable=True),
    sa.Column('inv_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inv_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inv_title', sa.String(length=256), nullable=True),
    sa.Column('inv_template_id', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('client_number', sa.String(length=64), nullable=True),
    sa.Column('client_company_name', sa.String(length=256), nullable=True),
    sa.Column('client_contact_name', sa.String(length=128), nullable=True),
    sa.Column('client_contact_title', sa.String(length=128), nullable=True),
    sa.Column('client_address', sa.String(length=512), nullable=True),
    sa.Column('client_email', sa.String(length=128), nullable=True),
    sa.Column('client_secondphone', sa.String(length=64), nullable=True),
    sa.Column('client_mainphone', sa.String(length=64), nullable=True),
    sa.Column('client_fax', sa.String(length=64), nullable=True),
    sa.Column('client_website', sa.String(length=256), nullable=True),
    sa.Column('client_business_number', sa.String(length=128), nullable=True),
    sa.Column('client_currency', sa.String(length=16), nullable=True),
    sa.Column('client_tax_id', sa.String(length=128), nullable=True),
    sa.Column('client_payment_term', sa.Integer(), nullable=True),
    sa.Column('client_payment_method', sa.String(length=64), nullable=True),
    sa.Column('client_terms_conditions', sa.String(length=1024), nullable=True),
    sa.Column('client_note', sa.String(length=1024), nullable=True),
    sa.Column('inv_payment_term', sa.Integer(), nullable=True),
    sa.Column('inv_payment_requirement', sa.String(length=256), nullable=True),
    sa.Column('inv_reference', sa.String(length=256), nullable=True),
    sa.Column('inv_currency', sa.String(length=16), nullable=True),
    sa.Column('inv_subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_tax_label', sa.String(length=64), nullable=True),
    sa.Column('inv_tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('inv_tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_shipping', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_handling', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_adjustment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_other_charges_label', sa.String(length=128), nullable=True),
    sa.Column('inv_other_charges_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_paid_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_balance_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_payment_status', sa.String(length=32), nullable=True),
    sa.Column('inv_tnc', sa.String(length=1024), nullable=True),
    sa.Column('inv_notes', sa.String(length=1024), nullable=True),
    sa.Column('inv_flag_word', sa.String(length=64), nullable=True),
    sa.Column('inv_flag_emoji', sa.String(length=16), nullable=True),
    sa.Column('inv_pdf_template', sa.String(length=64), nullable=True),
    sa.Column('inv_terms_conditions', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['too_global.zclient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ainvoaic'
    )
    op.create_index(op.f('ix_too_ainvoaic_invoice_biz_id'), 'invoice', ['biz_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_client_id'), 'invoice', ['client_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_created_by'), 'invoice', ['created_by'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_id'), 'invoice', ['id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_ten_id'), 'invoice', ['ten_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_usr_id'), 'invoice', ['usr_id'], unique=False, schema='too_ainvoaic')
    op.create_table('zbe',
    sa.Column('be_type', sa.String(), nullable=False),
    sa.Column('be_name', sa.String(), nullable=False),
    sa.Column('be_logo', sa.String(length=512), nullable=True),
    sa.Column('be_contact', sa.String(length=128), nullable=True),
    sa.Column('be_contact_title', sa.String(length=128), nullable=True),
    sa.Column('be_address', sa.String(length=512), nullable=True),
    sa.Column('be_email', sa.String(length=128), nullable=True),
    sa.Column('be_phone', sa.String(length=64), nullable=True),
    sa.Column('be_website', sa.String(length=256), nullable=True),
    sa.Column('be_biz_number', sa.String(length=128), nullable=True),
    sa.Column('be_tax_id', sa.String(length=128), nullable=True),
    sa.Column('be_bank_info', sa.String(length=1024), nullable=True),
    sa.Column('be_payment_term', sa.Integer(), nullable=True),
    sa.Column('be_currency', sa.String(length=16), nullable=True),
    sa.Column('be_inv_template_id', sa.String(length=32), nullable=True),
    sa.Column('be_description', sa.String(length=1024), nullable=True),
    sa.Column('be_note', sa.String(length=1024), nullable=True),
    sa.Column('be_timezone', sa.String(length=64), nullable=True),
    sa.Column('be_date_format', sa.String(length=32), nullable=True),
    sa.Column('be_inv_prefix', sa.String(length=32), nullable=True),
    sa.Column('be_inv_integer', sa.Integer(), nullable=True),
    sa.Column('be_inv_integer_max', sa.Integer(), nullable=True),
    sa.Column('be_show_paid_stamp', sa.Boolean(), nullable=True),
    sa.Column('be_plan_id', sa.Uuid(), nullable=True),
    sa.Column('be_plan_name', sa.String(length=128), nullable=True),
    sa.Column('be_plan251_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan252_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan253_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan254_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan255_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan256_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan257_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan258_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan259_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_number', sa.String(length=50), nullable=True),
    sa.Column('payroll_account_number', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(length=7), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('wsib_number', sa.String(), nullable=True),
    sa.Column('eht_account', sa.String(), nullable=True),
    sa.Column('remittance_frequency', sa.String(), nullable=True),
    sa.Column('tax_year_end', sa.Date(), nullable=True),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('operating_name', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('stripe_status', sa.String(), nullable=True),
    sa.Column('stripe_current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('stripe_cancel_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_plan_key', sa.String(), nullable=True),
    sa.Column('stripe_interval', sa.String(), nullable=True),
    sa.Column('stripe_latest_event_id', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['be_plan_id'], ['too_ainvoaic.plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='too_global'
    )
    op.create_index(op.f('ix_too_global_zbe_biz_id'), 'zbe', ['biz_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zbe_created_by'), 'zbe', ['created_by'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zbe_id'), 'zbe', ['id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zbe_stripe_customer_id'), 'zbe', ['stripe_customer_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zbe_stripe_subscription_id'), 'zbe', ['stripe_subscription_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zbe_ten_id'), 'zbe', ['ten_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zbe_usr_id'), 'zbe', ['usr_id'], unique=False, schema='too_global')
    op.create_table('invoice_item',
    sa.Column('inv_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('item_number', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=256), nullable=True),
    sa.Column('item_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('item_unit_of_measure', sa.String(length=64), nullable=True),
    sa.Column('item_unit', sa.String(length=64), nullable=True),
    sa.Column('item_sku', sa.String(length=128), nullable=True),
    sa.Column('item_description', sa.String(length=1024), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('item_note', sa.String(length=1024), nullable=True),
    sa.Column('item_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['inv_id'], ['too_ainvoaic.invoice.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['too_ainvoaic.item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ainvoaic'
    )
    op.create_index(op.f('ix_too_ainvoaic_invoice_item_biz_id'), 'invoice_item', ['biz_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_item_created_by'), 'invoice_item', ['created_by'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_item_id'), 'invoice_item', ['id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_item_inv_id'), 'invoice_item', ['inv_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_item_ten_id'), 'invoice_item', ['ten_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_item_usr_id'), 'invoice_item', ['usr_id'], unique=False, schema='too_ainvoaic')
    op.create_table('invoice_payment',
    sa.Column('inv_id', sa.Uuid(), nullable=False),
    sa.Column('pm_id', sa.Uuid(), nullable=True),
    sa.Column('pm_name', sa.String(length=128), nullable=True),
    sa.Column('pm_note', sa.String(length=1024), nullable=True),
    sa.Column('pay_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pay_reference', sa.String(length=256), nullable=True),
    sa.Column('pay_note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['inv_id'], ['too_ainvoaic.invoice.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['too_ainvoaic.i_payment_method.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ainvoaic'
    )
    op.create_index(op.f('ix_too_ainvoaic_invoice_payment_biz_id'), 'invoice_payment', ['biz_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_payment_created_by'), 'invoice_payment', ['created_by'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_payment_id'), 'invoice_payment', ['id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_payment_inv_id'), 'invoice_payment', ['inv_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_payment_ten_id'), 'invoice_payment', ['ten_id'], unique=False, schema='too_ainvoaic')
    op.create_index(op.f('ix_too_ainvoaic_invoice_payment_usr_id'), 'invoice_payment', ['usr_id'], unique=False, schema='too_ainvoaic')
    op.create_table('zuser_client',
    sa.Column('usr_id', sa.Uuid(), nullable=False),
    sa.Column('biz_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['biz_id'], ['too_global.zbe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usr_id'], ['too_global.zuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usr_id', 'biz_id', name='uq_user_client_user_biz'),
    schema='too_global'
    )
    op.create_index(op.f('ix_too_global_zuser_client_biz_id'), 'zuser_client', ['biz_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_client_created_by'), 'zuser_client', ['created_by'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_client_id'), 'zuser_client', ['id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_client_ten_id'), 'zuser_client', ['ten_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_client_usr_id'), 'zuser_client', ['usr_id'], unique=False, schema='too_global')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_global_zuser_client_usr_id'), table_name='zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_client_ten_id'), table_name='zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_client_id'), table_name='zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_client_created_by'), table_name='zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_client_biz_id'), table_name='zuser_client', schema='too_global')
    op.drop_table('zuser_client', schema='too_global')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_payment_usr_id'), table_name='invoice_payment', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_payment_ten_id'), table_name='invoice_payment', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_payment_inv_id'), table_name='invoice_payment', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_payment_id'), table_name='invoice_payment', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_payment_created_by'), table_name='invoice_payment', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_payment_biz_id'), table_name='invoice_payment', schema='too_ainvoaic')
    op.drop_table('invoice_payment', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_item_usr_id'), table_name='invoice_item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_item_ten_id'), table_name='invoice_item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_item_inv_id'), table_name='invoice_item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_item_id'), table_name='invoice_item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_item_created_by'), table_name='invoice_item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_item_biz_id'), table_name='invoice_item', schema='too_ainvoaic')
    op.drop_table('invoice_item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_global_zbe_usr_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_ten_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_stripe_subscription_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_stripe_customer_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_id'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_created_by'), table_name='zbe', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_biz_id'), table_name='zbe', schema='too_global')
    op.drop_table('zbe', schema='too_global')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_usr_id'), table_name='invoice', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_ten_id'), table_name='invoice', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_id'), table_name='invoice', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_created_by'), table_name='invoice', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_client_id'), table_name='invoice', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_invoice_biz_id'), table_name='invoice', schema='too_ainvoaic')
    op.drop_table('invoice', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_global_zuser_usr_id'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_ten_id'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_id'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_email'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_created_by'), table_name='zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_biz_id'), table_name='zuser', schema='too_global')
    op.drop_table('zuser', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_usr_id'), table_name='zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_ten_id'), table_name='zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_id'), table_name='zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_created_by'), table_name='zclient', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_biz_id'), table_name='zclient', schema='too_global')
    op.drop_table('zclient', schema='too_global')
    op.drop_index(op.f('ix_too_ainvoaic_taxes_usr_id'), table_name='taxes', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_taxes_ten_id'), table_name='taxes', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_taxes_id'), table_name='taxes', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_taxes_created_by'), table_name='taxes', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_taxes_biz_id'), table_name='taxes', schema='too_ainvoaic')
    op.drop_table('taxes', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_plans_usr_id'), table_name='plans', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_plans_ten_id'), table_name='plans', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_plans_id'), table_name='plans', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_plans_created_by'), table_name='plans', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_plans_biz_id'), table_name='plans', schema='too_ainvoaic')
    op.drop_table('plans', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_item_usr_id'), table_name='item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_item_ten_id'), table_name='item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_item_id'), table_name='item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_item_created_by'), table_name='item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_item_biz_id'), table_name='item', schema='too_ainvoaic')
    op.drop_table('item', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_i_payment_method_usr_id'), table_name='i_payment_method', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_i_payment_method_ten_id'), table_name='i_payment_method', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_i_payment_method_id'), table_name='i_payment_method', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_i_payment_method_created_by'), table_name='i_payment_method', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_i_payment_method_biz_id'), table_name='i_payment_method', schema='too_ainvoaic')
    op.drop_table('i_payment_method', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_fee_usr_id'), table_name='fee', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_fee_ten_id'), table_name='fee', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_fee_id'), table_name='fee', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_fee_created_by'), table_name='fee', schema='too_ainvoaic')
    op.drop_index(op.f('ix_too_ainvoaic_fee_biz_id'), table_name='fee', schema='too_ainvoaic')
    op.drop_table('fee', schema='too_ainvoaic')
    op.drop_index(op.f('ix_ai_cache_usr_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_ten_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_expires_at'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_created_by'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_cache_key'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_biz_id'), table_name='ai_cache')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
