"""draft

Revision ID: 148306e008c6
Revises: 112c885ceaca
Create Date: 2026-04-30 22:41:22.104125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '148306e008c6'
down_revision: Union[str, None] = '112c885ceaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_acc_je_draft_lines_biz_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_cli_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_created_by'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_ten_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_usr_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_table('je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_biz_id'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_cli_id'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_created_by'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_id'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_ten_id'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_usr_id'), table_name='je_drafts', schema='too_acc')
    op.drop_table('je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.create_table('je_drafts',
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ai_model', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('memo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ten_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('biz_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usr_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cli_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usr_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('b_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('b_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_decimal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('b_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('b_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('locale', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint('confidence >= 0::numeric AND confidence <= 1::numeric', name=op.f('ck_je_drafts_confidence')),
    sa.ForeignKeyConstraint(['transaction_id'], ['too_acc.transactions_raw.id'], name=op.f('je_drafts_transaction_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('je_drafts_pkey')),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_je_drafts_usr_id'), 'je_drafts', ['usr_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_ten_id'), 'je_drafts', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_id'), 'je_drafts', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_created_by'), 'je_drafts', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_cli_id'), 'je_drafts', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_biz_id'), 'je_drafts', ['biz_id'], unique=False, schema='too_acc')
    op.create_table('je_draft_lines',
    sa.Column('draft_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('line_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ten_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('biz_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usr_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cli_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usr_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('b_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('b_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_decimal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('b_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('b_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('locale', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint("line_type::text = ANY (ARRAY['debit'::character varying, 'credit'::character varying]::text[])", name=op.f('ck_je_draft_lines_line_type')),
    sa.CheckConstraint('amount > 0::numeric', name=op.f('ck_je_draft_lines_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['too_acc.coa.id'], name=op.f('je_draft_lines_account_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draft_id'], ['too_acc.je_drafts.id'], name=op.f('je_draft_lines_draft_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('je_draft_lines_pkey')),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_je_draft_lines_usr_id'), 'je_draft_lines', ['usr_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_ten_id'), 'je_draft_lines', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_id'), 'je_draft_lines', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_created_by'), 'je_draft_lines', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_cli_id'), 'je_draft_lines', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_biz_id'), 'je_draft_lines', ['biz_id'], unique=False, schema='too_acc')
    # ### end Alembic commands ###
