"""init6

Revision ID: 204c97e3a8de
Revises: 95c9fb61fa5b
Create Date: 2026-04-12 17:16:23.713692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '204c97e3a8de'
down_revision: Union[str, None] = '95c9fb61fa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_cache', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_cli_id'), 'ai_cache', ['cli_id'], unique=False, schema='too_ai')
    op.add_column('zbe', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_global')
    op.create_index(op.f('ix_too_global_zbe_cli_id'), 'zbe', ['cli_id'], unique=False, schema='too_global')
    op.add_column('zclient', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_global')
    op.create_index(op.f('ix_too_global_zclient_cli_id'), 'zclient', ['cli_id'], unique=False, schema='too_global')
    op.add_column('zuser', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_cli_id'), 'zuser', ['cli_id'], unique=False, schema='too_global')
    op.add_column('zuser_client', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_global')
    op.create_index(op.f('ix_too_global_zuser_client_cli_id'), 'zuser_client', ['cli_id'], unique=False, schema='too_global')
    op.add_column('ifee', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_inv')
    op.create_index(op.f('ix_too_inv_ifee_cli_id'), 'ifee', ['cli_id'], unique=False, schema='too_inv')
    op.add_column('invoice', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_inv')
    op.create_index(op.f('ix_too_inv_invoice_cli_id'), 'invoice', ['cli_id'], unique=False, schema='too_inv')
    op.add_column('invoice_item', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_inv')
    op.create_index(op.f('ix_too_inv_invoice_item_cli_id'), 'invoice_item', ['cli_id'], unique=False, schema='too_inv')
    op.add_column('invoice_payment', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_inv')
    op.create_index(op.f('ix_too_inv_invoice_payment_cli_id'), 'invoice_payment', ['cli_id'], unique=False, schema='too_inv')
    op.add_column('ipayment_method', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_inv')
    op.create_index(op.f('ix_too_inv_ipayment_method_cli_id'), 'ipayment_method', ['cli_id'], unique=False, schema='too_inv')
    op.add_column('iplan', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_inv')
    op.create_index(op.f('ix_too_inv_iplan_cli_id'), 'iplan', ['cli_id'], unique=False, schema='too_inv')
    op.add_column('itax', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_inv')
    op.create_index(op.f('ix_too_inv_itax_cli_id'), 'itax', ['cli_id'], unique=False, schema='too_inv')
    op.add_column('item', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_inv')
    op.create_index(op.f('ix_too_inv_item_cli_id'), 'item', ['cli_id'], unique=False, schema='too_inv')
    op.add_column('t4_employee', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_cli_id'), 't4_employee', ['cli_id'], unique=False, schema='too_t4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_t4_t4_employee_cli_id'), table_name='t4_employee', schema='too_t4')
    op.drop_column('t4_employee', 'cli_id', schema='too_t4')
    op.drop_index(op.f('ix_too_inv_item_cli_id'), table_name='item', schema='too_inv')
    op.drop_column('item', 'cli_id', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_itax_cli_id'), table_name='itax', schema='too_inv')
    op.drop_column('itax', 'cli_id', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_iplan_cli_id'), table_name='iplan', schema='too_inv')
    op.drop_column('iplan', 'cli_id', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ipayment_method_cli_id'), table_name='ipayment_method', schema='too_inv')
    op.drop_column('ipayment_method', 'cli_id', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_payment_cli_id'), table_name='invoice_payment', schema='too_inv')
    op.drop_column('invoice_payment', 'cli_id', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_item_cli_id'), table_name='invoice_item', schema='too_inv')
    op.drop_column('invoice_item', 'cli_id', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_invoice_cli_id'), table_name='invoice', schema='too_inv')
    op.drop_column('invoice', 'cli_id', schema='too_inv')
    op.drop_index(op.f('ix_too_inv_ifee_cli_id'), table_name='ifee', schema='too_inv')
    op.drop_column('ifee', 'cli_id', schema='too_inv')
    op.drop_index(op.f('ix_too_global_zuser_client_cli_id'), table_name='zuser_client', schema='too_global')
    op.drop_column('zuser_client', 'cli_id', schema='too_global')
    op.drop_index(op.f('ix_too_global_zuser_cli_id'), table_name='zuser', schema='too_global')
    op.drop_column('zuser', 'cli_id', schema='too_global')
    op.drop_index(op.f('ix_too_global_zclient_cli_id'), table_name='zclient', schema='too_global')
    op.drop_column('zclient', 'cli_id', schema='too_global')
    op.drop_index(op.f('ix_too_global_zbe_cli_id'), table_name='zbe', schema='too_global')
    op.drop_column('zbe', 'cli_id', schema='too_global')
    op.drop_index(op.f('ix_too_ai_ai_cache_cli_id'), table_name='ai_cache', schema='too_ai')
    op.drop_column('ai_cache', 'cli_id', schema='too_ai')
    # ### end Alembic commands ###
