"""1024

Revision ID: 3f7159049e2a
Revises: 04a2ed89e97f
Create Date: 2026-04-26 01:05:51.170390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
# revision identifiers, used by Alembic.
revision: str = '3f7159049e2a'
down_revision: Union[str, None] = '04a2ed89e97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv_1024', sa.Column('ten_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('created_by', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='too_ai')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_too_ai_inv_1024_created_by'), 'inv_1024', ['created_by'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_ten_id'), 'inv_1024', ['ten_id'], unique=False, schema='too_ai')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_too_ai_inv_1024_ten_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_created_by'), table_name='inv_1024', schema='too_ai')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_column('inv_1024', 'created_at', schema='too_ai')
    op.drop_column('inv_1024', 'created_by', schema='too_ai')
    op.drop_column('inv_1024', 'ten_id', schema='too_ai')
    # ### end Alembic commands ###
