"""init3

Revision ID: 3f9924c1a814
Revises: 55f531ecc1ce
Create Date: 2026-04-16 00:19:29.940749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '3f9924c1a814'
down_revision: Union[str, None] = '55f531ecc1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_history_384',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk', sa.Text(), nullable=False),
    sa.Column('text_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('emb384', Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, postgresql_using='gin')
    op.create_index('ix_emb384_hnsw', 'payroll_history_384', ['emb384'], unique=False, postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    op.create_index(op.f('ix_payroll_history_384_id'), 'payroll_history_384', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_history_384_source_id'), 'payroll_history_384', ['source_id'], unique=False)
    op.create_table('ai_feedback_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('feedback_type', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_index(op.f('ix_too_ai_ai_feedback_event_biz_id'), 'ai_feedback_event', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_feedback_type'), 'ai_feedback_event', ['feedback_type'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_message_id'), 'ai_feedback_event', ['message_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_model'), 'ai_feedback_event', ['model'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_route'), 'ai_feedback_event', ['route'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_session_id'), 'ai_feedback_event', ['session_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_ten_id'), 'ai_feedback_event', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_user_id'), 'ai_feedback_event', ['user_id'], unique=False, schema='too_ai')
    op.create_table('ai_guardrail_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('judge_model', sa.Text(), nullable=True),
    sa.Column('is_hallucination', sa.Boolean(), nullable=True),
    sa.Column('is_refusal', sa.Boolean(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_biz_id'), 'ai_guardrail_event', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_model'), 'ai_guardrail_event', ['model'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_route'), 'ai_guardrail_event', ['route'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_ten_id'), 'ai_guardrail_event', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_user_id'), 'ai_guardrail_event', ['user_id'], unique=False, schema='too_ai')
    op.create_table('rag_eval_dataset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('relevant_source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_table('rag_eval_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('embedding_version', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_table('employees',
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), sa.Computed("first_name || ' ' || last_name", persisted=True), nullable=False),
    sa.Column('sin', sa.String(length=9), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('regular_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('federal_claim_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ontario_claim_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpp_exempt', sa.Boolean(), nullable=True),
    sa.Column('ei_exempt', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_t4'
    )
    op.create_index(op.f('ix_too_t4_employees_biz_id'), 'employees', ['biz_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_employees_cli_id'), 'employees', ['cli_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_employees_created_by'), 'employees', ['created_by'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_employees_id'), 'employees', ['id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_employees_ten_id'), 'employees', ['ten_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_employees_usr_id'), 'employees', ['usr_id'], unique=False, schema='too_t4')
    op.create_table('payroll_schedules',
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payon', sa.String(), nullable=False),
    sa.Column('semi1', sa.String(), nullable=False),
    sa.Column('semi2', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_t4'
    )
    op.create_index(op.f('ix_too_t4_payroll_schedules_biz_id'), 'payroll_schedules', ['biz_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_schedules_cli_id'), 'payroll_schedules', ['cli_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_schedules_created_by'), 'payroll_schedules', ['created_by'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_schedules_id'), 'payroll_schedules', ['id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_schedules_ten_id'), 'payroll_schedules', ['ten_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_schedules_usr_id'), 'payroll_schedules', ['usr_id'], unique=False, schema='too_t4')
    op.create_table('rag_eval_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved_source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('recall_at_k', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('precision_at_k', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('is_faithful', sa.Boolean(), nullable=True),
    sa.Column('eval_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['too_ai.rag_eval_dataset.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['too_ai.rag_eval_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_index(op.f('ix_too_ai_rag_eval_result_dataset_id'), 'rag_eval_result', ['dataset_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_rag_eval_result_run_id'), 'rag_eval_result', ['run_id'], unique=False, schema='too_ai')
    op.create_table('payroll_periods',
    sa.Column('payroll_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('period_key', sa.String(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['payroll_schedule_id'], ['too_t4.payroll_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_id', 'period_key', name='uq_payroll_period_key'),
    schema='too_t4'
    )
    op.create_index(op.f('ix_too_t4_payroll_periods_biz_id'), 'payroll_periods', ['biz_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_cli_id'), 'payroll_periods', ['cli_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_created_by'), 'payroll_periods', ['created_by'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_end_date'), 'payroll_periods', ['end_date'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_id'), 'payroll_periods', ['id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_pay_date'), 'payroll_periods', ['pay_date'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_payroll_schedule_id'), 'payroll_periods', ['payroll_schedule_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_period_key'), 'payroll_periods', ['period_key'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_start_date'), 'payroll_periods', ['start_date'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_ten_id'), 'payroll_periods', ['ten_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_periods_usr_id'), 'payroll_periods', ['usr_id'], unique=False, schema='too_t4')
    op.create_table('payroll_entries',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('payroll_period_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('period_key', sa.String(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('annual_salary_snapshot', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hourly_rate_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('federal_claim_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ontario_claim_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('regular_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vacation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cpp', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ei', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_deduction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('adjustment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cpp_exempt_snapshot', sa.Boolean(), nullable=False),
    sa.Column('ei_exempt_snapshot', sa.Boolean(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['too_t4.employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['too_t4.payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['too_t4.payroll_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='too_t4'
    )
    op.create_index(op.f('ix_too_t4_payroll_entries_biz_id'), 'payroll_entries', ['biz_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_cli_id'), 'payroll_entries', ['cli_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_created_by'), 'payroll_entries', ['created_by'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_employee_id'), 'payroll_entries', ['employee_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_id'), 'payroll_entries', ['id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_pay_date'), 'payroll_entries', ['pay_date'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_payroll_period_id'), 'payroll_entries', ['payroll_period_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_period_end'), 'payroll_entries', ['period_end'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_period_key'), 'payroll_entries', ['period_key'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_period_start'), 'payroll_entries', ['period_start'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_schedule_id'), 'payroll_entries', ['schedule_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_ten_id'), 'payroll_entries', ['ten_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_entries_usr_id'), 'payroll_entries', ['usr_id'], unique=False, schema='too_t4')
    op.create_table('payroll_history',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('payroll_period_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_key', sa.String(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('annual_salary_snapshot', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hourly_rate_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('federal_claim_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ontario_claim_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('regular_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vacation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cpp', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ei', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_deduction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('adjustment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cpp_exempt_snapshot', sa.Boolean(), nullable=False),
    sa.Column('ei_exempt_snapshot', sa.Boolean(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['too_t4.employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['too_t4.payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['too_t4.payroll_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='too_t4'
    )
    op.create_index(op.f('ix_too_t4_payroll_history_biz_id'), 'payroll_history', ['biz_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_cli_id'), 'payroll_history', ['cli_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_created_by'), 'payroll_history', ['created_by'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_employee_id'), 'payroll_history', ['employee_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_id'), 'payroll_history', ['id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_payroll_period_id'), 'payroll_history', ['payroll_period_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_period_end'), 'payroll_history', ['period_end'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_period_key'), 'payroll_history', ['period_key'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_period_start'), 'payroll_history', ['period_start'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_schedule_id'), 'payroll_history', ['schedule_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_ten_id'), 'payroll_history', ['ten_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_payroll_history_usr_id'), 'payroll_history', ['usr_id'], unique=False, schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_biz_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_cli_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_created_by'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_ten_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_usr_id'), table_name='t4_employee', schema='too_t4')
    op.drop_table('t4_employee', schema='too_t4')
    op.drop_constraint(op.f('invoice_client_id_fkey'), 'invoice', schema='too_inv', type_='foreignkey')
    op.drop_constraint(op.f('invoice_item_inv_id_fkey'), 'invoice_item', schema='too_inv', type_='foreignkey')
    op.drop_constraint(op.f('invoice_item_item_id_fkey'), 'invoice_item', schema='too_inv', type_='foreignkey')
    op.drop_constraint(op.f('invoice_payment_inv_id_fkey'), 'invoice_payment', schema='too_inv', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('invoice_payment_inv_id_fkey'), 'invoice_payment', 'invoice', ['inv_id'], ['id'], source_schema='too_inv', referent_schema='too_inv')
    op.create_foreign_key(op.f('invoice_item_item_id_fkey'), 'invoice_item', 'item', ['item_id'], ['id'], source_schema='too_inv', referent_schema='too_inv')
    op.create_foreign_key(op.f('invoice_item_inv_id_fkey'), 'invoice_item', 'invoice', ['inv_id'], ['id'], source_schema='too_inv', referent_schema='too_inv')
    op.create_foreign_key(op.f('invoice_client_id_fkey'), 'invoice', 'zclient', ['client_id'], ['id'], source_schema='too_inv', referent_schema='too_global')
    op.create_table('t4_employee',
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), sa.Computed("(((first_name)::text || ' '::text) || (last_name)::text)", persisted=True), autoincrement=False, nullable=False),
    sa.Column('sin', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('annual_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('regular_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('federal_claim_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('ontario_claim_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('cpp_exempt', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ei_exempt', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ten_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('biz_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usr_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usr_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('b_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('b_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_decimal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('b_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('b_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('locale', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cli_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('t4_employee_pkey')),
    schema='too_t4'
    )
    op.create_index(op.f('ix_too_t4_t4_employee_usr_id'), 't4_employee', ['usr_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_ten_id'), 't4_employee', ['ten_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_id'), 't4_employee', ['id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_created_by'), 't4_employee', ['created_by'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_cli_id'), 't4_employee', ['cli_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_biz_id'), 't4_employee', ['biz_id'], unique=False, schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_usr_id'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_ten_id'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_schedule_id'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_period_start'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_period_key'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_period_end'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_payroll_period_id'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_id'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_employee_id'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_created_by'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_cli_id'), table_name='payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_history_biz_id'), table_name='payroll_history', schema='too_t4')
    op.drop_table('payroll_history', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_usr_id'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_ten_id'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_schedule_id'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_period_start'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_period_key'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_period_end'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_payroll_period_id'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_pay_date'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_id'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_employee_id'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_created_by'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_cli_id'), table_name='payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_entries_biz_id'), table_name='payroll_entries', schema='too_t4')
    op.drop_table('payroll_entries', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_usr_id'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_ten_id'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_start_date'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_period_key'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_payroll_schedule_id'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_pay_date'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_id'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_end_date'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_created_by'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_cli_id'), table_name='payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_periods_biz_id'), table_name='payroll_periods', schema='too_t4')
    op.drop_table('payroll_periods', schema='too_t4')
    op.drop_index(op.f('ix_too_ai_rag_eval_result_run_id'), table_name='rag_eval_result', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_rag_eval_result_dataset_id'), table_name='rag_eval_result', schema='too_ai')
    op.drop_table('rag_eval_result', schema='too_ai')
    op.drop_index(op.f('ix_too_t4_payroll_schedules_usr_id'), table_name='payroll_schedules', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_schedules_ten_id'), table_name='payroll_schedules', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_schedules_id'), table_name='payroll_schedules', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_schedules_created_by'), table_name='payroll_schedules', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_schedules_cli_id'), table_name='payroll_schedules', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_payroll_schedules_biz_id'), table_name='payroll_schedules', schema='too_t4')
    op.drop_table('payroll_schedules', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_employees_usr_id'), table_name='employees', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_employees_ten_id'), table_name='employees', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_employees_id'), table_name='employees', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_employees_created_by'), table_name='employees', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_employees_cli_id'), table_name='employees', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_employees_biz_id'), table_name='employees', schema='too_t4')
    op.drop_table('employees', schema='too_t4')
    op.drop_table('rag_eval_run', schema='too_ai')
    op.drop_table('rag_eval_dataset', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_user_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_ten_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_route'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_model'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_biz_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_table('ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_user_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_ten_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_session_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_route'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_model'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_message_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_feedback_type'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_biz_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_table('ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_payroll_history_384_source_id'), table_name='payroll_history_384')
    op.drop_index(op.f('ix_payroll_history_384_id'), table_name='payroll_history_384')
    op.drop_index('ix_emb384_hnsw', table_name='payroll_history_384', postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', postgresql_using='gin')
    op.drop_table('payroll_history_384')
    # ### end Alembic commands ###
