"""init5

Revision ID: 95c9fb61fa5b
Revises: f2d766eb3d0f
Create Date: 2026-04-11 21:38:01.376102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '95c9fb61fa5b'
down_revision: Union[str, None] = 'f2d766eb3d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'cache_key', name='uq_agent_cache_ten_key'),
    schema='too_ai'
    )
    op.create_index(op.f('ix_too_ai_ai_cache_biz_id'), 'ai_cache', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_cache_key'), 'ai_cache', ['cache_key'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_created_by'), 'ai_cache', ['created_by'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_expires_at'), 'ai_cache', ['expires_at'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_id'), 'ai_cache', ['id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_ten_id'), 'ai_cache', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_usr_id'), 'ai_cache', ['usr_id'], unique=False, schema='too_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_ai_ai_cache_usr_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_ten_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_expires_at'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_created_by'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_cache_key'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_biz_id'), table_name='ai_cache', schema='too_ai')
    op.drop_table('ai_cache', schema='too_ai')
    # ### end Alembic commands ###
