"""1024

Revision ID: a251c3ac169f
Revises: 3f7159049e2a
Create Date: 2026-04-28 12:00:27.800180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a251c3ac169f'
down_revision: Union[str, None] = '3f7159049e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv_1024', sa.Column('chunk_id', sa.Integer(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('biz_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('usr_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('usr_type', sa.String(length=32), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('b_int', sa.Integer(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('b_str', sa.String(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('b_date', sa.DateTime(timezone=True), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('b_bool', sa.Boolean(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('is_deleted', sa.Boolean(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('is_flag', sa.Boolean(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('locale', sa.String(length=32), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('status', sa.String(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('type', sa.String(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('description', sa.String(), nullable=True), schema='too_ai')
    op.add_column('inv_1024', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='too_ai')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_too_ai_inv_1024_biz_id'), 'inv_1024', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_cli_id'), 'inv_1024', ['cli_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_usr_id'), 'inv_1024', ['usr_id'], unique=False, schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('chunk_id', sa.Integer(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('ten_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('biz_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('usr_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('usr_type', sa.String(length=32), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('created_by', sa.Uuid(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('b_int', sa.Integer(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('b_str', sa.String(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('b_date', sa.DateTime(timezone=True), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('b_bool', sa.Boolean(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('is_deleted', sa.Boolean(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('is_flag', sa.Boolean(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('locale', sa.String(length=32), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('status', sa.String(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('type', sa.String(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('description', sa.String(), nullable=True), schema='too_ai')
    op.add_column('payroll_history_384', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='too_ai')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_too_ai_payroll_history_384_biz_id'), 'payroll_history_384', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_cli_id'), 'payroll_history_384', ['cli_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_created_by'), 'payroll_history_384', ['created_by'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_ten_id'), 'payroll_history_384', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_usr_id'), 'payroll_history_384', ['usr_id'], unique=False, schema='too_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_ai_payroll_history_384_usr_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_ten_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_created_by'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_cli_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_biz_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_column('payroll_history_384', 'extra', schema='too_ai')
    op.drop_column('payroll_history_384', 'description', schema='too_ai')
    op.drop_column('payroll_history_384', 'type', schema='too_ai')
    op.drop_column('payroll_history_384', 'status', schema='too_ai')
    op.drop_column('payroll_history_384', 'locale', schema='too_ai')
    op.drop_column('payroll_history_384', 'is_flag', schema='too_ai')
    op.drop_column('payroll_history_384', 'is_deleted', schema='too_ai')
    op.drop_column('payroll_history_384', 'b_json', schema='too_ai')
    op.drop_column('payroll_history_384', 'b_bool', schema='too_ai')
    op.drop_column('payroll_history_384', 'b_date', schema='too_ai')
    op.drop_column('payroll_history_384', 'b_decimal', schema='too_ai')
    op.drop_column('payroll_history_384', 'b_str', schema='too_ai')
    op.drop_column('payroll_history_384', 'b_int', schema='too_ai')
    op.drop_column('payroll_history_384', 'created_at', schema='too_ai')
    op.drop_column('payroll_history_384', 'created_by', schema='too_ai')
    op.drop_column('payroll_history_384', 'usr_type', schema='too_ai')
    op.drop_column('payroll_history_384', 'cli_id', schema='too_ai')
    op.drop_column('payroll_history_384', 'usr_id', schema='too_ai')
    op.drop_column('payroll_history_384', 'biz_id', schema='too_ai')
    op.drop_column('payroll_history_384', 'ten_id', schema='too_ai')
    op.drop_column('payroll_history_384', 'chunk_id', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_usr_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_cli_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_biz_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_column('inv_1024', 'extra', schema='too_ai')
    op.drop_column('inv_1024', 'description', schema='too_ai')
    op.drop_column('inv_1024', 'type', schema='too_ai')
    op.drop_column('inv_1024', 'status', schema='too_ai')
    op.drop_column('inv_1024', 'locale', schema='too_ai')
    op.drop_column('inv_1024', 'is_flag', schema='too_ai')
    op.drop_column('inv_1024', 'is_deleted', schema='too_ai')
    op.drop_column('inv_1024', 'b_json', schema='too_ai')
    op.drop_column('inv_1024', 'b_bool', schema='too_ai')
    op.drop_column('inv_1024', 'b_date', schema='too_ai')
    op.drop_column('inv_1024', 'b_decimal', schema='too_ai')
    op.drop_column('inv_1024', 'b_str', schema='too_ai')
    op.drop_column('inv_1024', 'b_int', schema='too_ai')
    op.drop_column('inv_1024', 'usr_type', schema='too_ai')
    op.drop_column('inv_1024', 'cli_id', schema='too_ai')
    op.drop_column('inv_1024', 'usr_id', schema='too_ai')
    op.drop_column('inv_1024', 'biz_id', schema='too_ai')
    op.drop_column('inv_1024', 'chunk_id', schema='too_ai')
    # ### end Alembic commands ###
