"""acc_mcp

Revision ID: b22e538c8483
Revises: 148306e008c6
Create Date: 2026-05-02 23:35:52.482183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b22e538c8483'
down_revision: Union[str, None] = '148306e008c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('posted_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_mcp_bank_transactions_account_name'), 'mcp_bank_transactions', ['account_name'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_mcp_bank_transactions_posted_at'), 'mcp_bank_transactions', ['posted_at'], unique=False, schema='too_acc')
    op.create_table('mcp_vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_mcp_vendors_name'), 'mcp_vendors', ['name'], unique=True, schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_too_acc_mcp_vendors_name'), table_name='mcp_vendors', schema='too_acc')
    op.drop_table('mcp_vendors', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_mcp_bank_transactions_posted_at'), table_name='mcp_bank_transactions', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_mcp_bank_transactions_account_name'), table_name='mcp_bank_transactions', schema='too_acc')
    op.drop_table('mcp_bank_transactions', schema='too_acc')
    # ### end Alembic commands ###
