"""acc

Revision ID: c7a539dd3235
Revises: a251c3ac169f
Create Date: 2026-04-29 23:05:02.427724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c7a539dd3235'
down_revision: Union[str, None] = 'a251c3ac169f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_audit_events_biz_id'), 'audit_events', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_cli_id'), 'audit_events', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_created_by'), 'audit_events', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_id'), 'audit_events', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_ten_id'), 'audit_events', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_usr_id'), 'audit_events', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('coa',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("type in ('asset','liability','equity','revenue','expense')", name='ck_accounts_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'code', name='uq_accounts_owner_code'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_coa_biz_id'), 'coa', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_cli_id'), 'coa', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_created_by'), 'coa', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_id'), 'coa', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_ten_id'), 'coa', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_usr_id'), 'coa', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('journal_entries',
    sa.Column('entry_no', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('source_ref_id', sa.Uuid(), nullable=True),
    sa.Column('posted_by', sa.Uuid(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('period_yyyymm', sa.Integer(), nullable=False),
    sa.Column('is_reversal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reversed_entry_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("source in ('manual','ai','import','reversal')", name='ck_journal_entries_source'),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['too_acc.journal_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'entry_no', name='uq_journal_entries_owner_entry_no'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_journal_entries_biz_id'), 'journal_entries', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_cli_id'), 'journal_entries', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_created_by'), 'journal_entries', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_id'), 'journal_entries', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_ten_id'), 'journal_entries', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_usr_id'), 'journal_entries', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('period_closes',
    sa.Column('period_yyyymm', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'period_yyyymm', name='uq_period_closes_owner_period'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_period_closes_biz_id'), 'period_closes', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_cli_id'), 'period_closes', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_created_by'), 'period_closes', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_id'), 'period_closes', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_ten_id'), 'period_closes', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_usr_id'), 'period_closes', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('transactions_raw',
    sa.Column('source', sa.String(length=20), server_default=sa.text("'csv'"), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'CAD'"), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status in ('new','mapped','needs_review','posted')", name='ck_transactions_raw_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'hash', name='uq_transactions_owner_hash'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_transactions_raw_biz_id'), 'transactions_raw', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_cli_id'), 'transactions_raw', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_created_by'), 'transactions_raw', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_id'), 'transactions_raw', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_ten_id'), 'transactions_raw', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_usr_id'), 'transactions_raw', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('je_drafts',
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('ai_model', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('confidence >= 0 and confidence <= 1', name='ck_je_drafts_confidence'),
    sa.ForeignKeyConstraint(['transaction_id'], ['too_acc.transactions_raw.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_je_drafts_biz_id'), 'je_drafts', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_cli_id'), 'je_drafts', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_created_by'), 'je_drafts', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_id'), 'je_drafts', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_ten_id'), 'je_drafts', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_drafts_usr_id'), 'je_drafts', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('journal_entry_lines',
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('line_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("line_type in ('debit','credit')", name='ck_journal_entry_lines_line_type'),
    sa.CheckConstraint('amount > 0', name='ck_journal_entry_lines_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['too_acc.coa.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['too_acc.journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_journal_entry_lines_biz_id'), 'journal_entry_lines', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_cli_id'), 'journal_entry_lines', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_created_by'), 'journal_entry_lines', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_id'), 'journal_entry_lines', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_ten_id'), 'journal_entry_lines', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_usr_id'), 'journal_entry_lines', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('je_draft_lines',
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('line_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("line_type in ('debit','credit')", name='ck_je_draft_lines_line_type'),
    sa.CheckConstraint('amount > 0', name='ck_je_draft_lines_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['too_acc.coa.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draft_id'], ['too_acc.je_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_je_draft_lines_biz_id'), 'je_draft_lines', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_cli_id'), 'je_draft_lines', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_created_by'), 'je_draft_lines', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_id'), 'je_draft_lines', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_ten_id'), 'je_draft_lines', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_je_draft_lines_usr_id'), 'je_draft_lines', ['usr_id'], unique=False, schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_usr_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_ten_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_created_by'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_cli_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_draft_lines_biz_id'), table_name='je_draft_lines', schema='too_acc')
    op.drop_table('je_draft_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_usr_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_ten_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_created_by'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_cli_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_biz_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_table('journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_usr_id'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_ten_id'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_id'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_created_by'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_cli_id'), table_name='je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_je_drafts_biz_id'), table_name='je_drafts', schema='too_acc')
    op.drop_table('je_drafts', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_usr_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_ten_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_created_by'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_cli_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_biz_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_table('transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_usr_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_ten_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_created_by'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_cli_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_biz_id'), table_name='period_closes', schema='too_acc')
    op.drop_table('period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_usr_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_ten_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_created_by'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_cli_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_biz_id'), table_name='journal_entries', schema='too_acc')
    op.drop_table('journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_usr_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_ten_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_created_by'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_cli_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_biz_id'), table_name='coa', schema='too_acc')
    op.drop_table('coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_usr_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_ten_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_created_by'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_cli_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_biz_id'), table_name='audit_events', schema='too_acc')
    op.drop_table('audit_events', schema='too_acc')
    # ### end Alembic commands ###
