"""draft

Revision ID: d6c6cf54db32
Revises: c7a539dd3235
Create Date: 2026-04-30 22:35:11.396242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd6c6cf54db32'
down_revision: Union[str, None] = 'c7a539dd3235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_usr_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_ten_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_created_by'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_cli_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_biz_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_table('journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_usr_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_ten_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_created_by'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_cli_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_biz_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_table('transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_usr_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_ten_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_created_by'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_cli_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_biz_id'), table_name='period_closes', schema='too_acc')
    op.drop_table('period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_usr_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_ten_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_created_by'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_cli_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_biz_id'), table_name='journal_entries', schema='too_acc')
    op.drop_table('journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_usr_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_ten_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_created_by'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_cli_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_biz_id'), table_name='coa', schema='too_acc')
    op.drop_table('coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_usr_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_ten_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_created_by'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_cli_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_biz_id'), table_name='audit_events', schema='too_acc')
    op.drop_table('audit_events', schema='too_acc')
    # ### end Alembic commands ###
