"""init

Revision ID: e51e780e93d0
Revises: 3f9924c1a814
Create Date: 2026-04-16 12:11:15.276109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e51e780e93d0'
down_revision: Union[str, None] = '3f9924c1a814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_history_384',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk', sa.Text(), nullable=False),
    sa.Column('text_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('emb384', Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, postgresql_using='gin')
    op.create_index('ix_emb384_hnsw', 'payroll_history_384', ['emb384'], unique=False, postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    op.create_index(op.f('ix_payroll_history_384_id'), 'payroll_history_384', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_history_384_source_id'), 'payroll_history_384', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_history_384_source_id'), table_name='payroll_history_384')
    op.drop_index(op.f('ix_payroll_history_384_id'), table_name='payroll_history_384')
    op.drop_index('ix_emb384_hnsw', table_name='payroll_history_384', postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', postgresql_using='gin')
    op.drop_table('payroll_history_384')
    # ### end Alembic commands ###
