"""init4

Revision ID: e8eddd478f94
Revises: 03197a06b7cb
Create Date: 2026-04-11 21:33:27.688434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e8eddd478f94'
down_revision: Union[str, None] = '03197a06b7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'cache_key', name='uq_agent_cache_ten_key')
    )
    op.create_index(op.f('ix_ai_cache_biz_id'), 'ai_cache', ['biz_id'], unique=False)
    op.create_index(op.f('ix_ai_cache_cache_key'), 'ai_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_ai_cache_created_by'), 'ai_cache', ['created_by'], unique=False)
    op.create_index(op.f('ix_ai_cache_expires_at'), 'ai_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ai_cache_id'), 'ai_cache', ['id'], unique=False)
    op.create_index(op.f('ix_ai_cache_ten_id'), 'ai_cache', ['ten_id'], unique=False)
    op.create_index(op.f('ix_ai_cache_usr_id'), 'ai_cache', ['usr_id'], unique=False)
    op.create_table('t4_employee',
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), sa.Computed("first_name || ' ' || last_name", persisted=True), nullable=False),
    sa.Column('sin', sa.String(length=9), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('regular_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('federal_claim_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ontario_claim_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpp_exempt', sa.Boolean(), nullable=True),
    sa.Column('ei_exempt', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_t4'
    )
    op.create_index(op.f('ix_too_t4_t4_employee_biz_id'), 't4_employee', ['biz_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_created_by'), 't4_employee', ['created_by'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_id'), 't4_employee', ['id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_ten_id'), 't4_employee', ['ten_id'], unique=False, schema='too_t4')
    op.create_index(op.f('ix_too_t4_t4_employee_usr_id'), 't4_employee', ['usr_id'], unique=False, schema='too_t4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_t4_t4_employee_usr_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_ten_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_id'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_created_by'), table_name='t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_too_t4_t4_employee_biz_id'), table_name='t4_employee', schema='too_t4')
    op.drop_table('t4_employee', schema='too_t4')
    op.drop_index(op.f('ix_ai_cache_usr_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_ten_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_id'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_expires_at'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_created_by'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_cache_key'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_biz_id'), table_name='ai_cache')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
